###
GET http://127.0.0.1:8095/rest/users2/deleteById?id=2
content-type:application/json;charset=UTF-8
locale:zh

###
GET http://127.0.0.1:8095/rest/users/getById?id=2
content-type:application/json;charset=UTF-8
locale:zh

###


###
GET http://127.0.0.1:8095/rest/users2/findForPage?pageNum=1&pageSize=2
content-type:application/json;charset=UTF-8
locale:zh

###
###
GET http://127.0.0.1:8095/rest/users2/findForPage?pageNum=1&pageSize=2&name=Sam
content-type:application/json;charset=UTF-8
locale:zh

###
